-- ============================================================
-- Real Estate Management System - Oracle DDL Script
-- Schema: as configured in secrets
-- ============================================================

-- ============================================================
-- SEQUENCES
-- ============================================================
CREATE SEQUENCE SEQ_USERS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_UNIT_TYPES     START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROJECTS       START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_BUILDINGS      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_FLOORS         START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CUSTOMERS      START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_UNITS          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_SALES          START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_UNIT_IMAGES    START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- ============================================================
-- TABLE: USERS
-- ============================================================
CREATE TABLE USERS (
    USER_ID       NUMBER        NOT NULL,
    USERNAME      VARCHAR2(100) NOT NULL,
    PASSWORD_HASH VARCHAR2(255) NOT NULL,
    FULL_NAME     VARCHAR2(200) NOT NULL,
    EMAIL         VARCHAR2(200),
    ROLE          VARCHAR2(50)  NOT NULL CHECK (ROLE IN ('ADMIN','ACCOUNTING')),
    IS_ACTIVE     NUMBER(1)     DEFAULT 1 NOT NULL,
    CREATED_BY    VARCHAR2(100),
    CREATED_DATE  DATE          DEFAULT SYSDATE,
    UPDATED_BY    VARCHAR2(100),
    UPDATED_DATE  DATE,
    CONSTRAINT PK_USERS PRIMARY KEY (USER_ID),
    CONSTRAINT UQ_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UQ_USERS_EMAIL UNIQUE (EMAIL)
);

CREATE TRIGGER TRG_USERS_ID
  BEFORE INSERT ON USERS
  FOR EACH ROW
BEGIN
  IF :NEW.USER_ID IS NULL THEN
    SELECT SEQ_USERS.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_USERS_USERNAME ON USERS (USERNAME);

-- ============================================================
-- TABLE: UNIT_TYPES
-- ============================================================
CREATE TABLE UNIT_TYPES (
    TYPE_ID      NUMBER        NOT NULL,
    TYPE_NAME    VARCHAR2(200) NOT NULL,
    DESCRIPTION  VARCHAR2(500),
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE          DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_UNIT_TYPES PRIMARY KEY (TYPE_ID),
    CONSTRAINT UQ_UNIT_TYPES_NAME UNIQUE (TYPE_NAME)
);

CREATE TRIGGER TRG_UNIT_TYPES_ID
  BEFORE INSERT ON UNIT_TYPES
  FOR EACH ROW
BEGIN
  IF :NEW.TYPE_ID IS NULL THEN
    SELECT SEQ_UNIT_TYPES.NEXTVAL INTO :NEW.TYPE_ID FROM DUAL;
  END IF;
END;
/

-- ============================================================
-- TABLE: PROJECTS
-- ============================================================
CREATE TABLE PROJECTS (
    PROJECT_ID   NUMBER        NOT NULL,
    PROJECT_NAME VARCHAR2(300) NOT NULL,
    LOCATION     VARCHAR2(500),
    DESCRIPTION  VARCHAR2(2000),
    START_DATE   DATE,
    END_DATE     DATE,
    STATUS       VARCHAR2(50)  DEFAULT 'ACTIVE' CHECK (STATUS IN ('ACTIVE','COMPLETED','ON_HOLD')),
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE          DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_PROJECTS PRIMARY KEY (PROJECT_ID)
);

CREATE TRIGGER TRG_PROJECTS_ID
  BEFORE INSERT ON PROJECTS
  FOR EACH ROW
BEGIN
  IF :NEW.PROJECT_ID IS NULL THEN
    SELECT SEQ_PROJECTS.NEXTVAL INTO :NEW.PROJECT_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_PROJECTS_STATUS ON PROJECTS (STATUS);

-- ============================================================
-- TABLE: BUILDINGS
-- ============================================================
CREATE TABLE BUILDINGS (
    BUILDING_ID   NUMBER        NOT NULL,
    PROJECT_ID    NUMBER        NOT NULL,
    BUILDING_NAME VARCHAR2(300) NOT NULL,
    BUILDING_CODE VARCHAR2(100),
    FLOORS_COUNT  NUMBER        DEFAULT 0,
    DESCRIPTION   VARCHAR2(2000),
    CREATED_BY    VARCHAR2(100),
    CREATED_DATE  DATE          DEFAULT SYSDATE,
    UPDATED_BY    VARCHAR2(100),
    UPDATED_DATE  DATE,
    CONSTRAINT PK_BUILDINGS PRIMARY KEY (BUILDING_ID),
    CONSTRAINT FK_BUILDINGS_PROJECT FOREIGN KEY (PROJECT_ID) REFERENCES PROJECTS(PROJECT_ID)
);

CREATE TRIGGER TRG_BUILDINGS_ID
  BEFORE INSERT ON BUILDINGS
  FOR EACH ROW
BEGIN
  IF :NEW.BUILDING_ID IS NULL THEN
    SELECT SEQ_BUILDINGS.NEXTVAL INTO :NEW.BUILDING_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_BUILDINGS_PROJECT ON BUILDINGS (PROJECT_ID);

-- ============================================================
-- TABLE: FLOORS
-- ============================================================
CREATE TABLE FLOORS (
    FLOOR_ID     NUMBER        NOT NULL,
    BUILDING_ID  NUMBER        NOT NULL,
    FLOOR_NUMBER VARCHAR2(50)  NOT NULL,
    FLOOR_NAME   VARCHAR2(200),
    DESCRIPTION  VARCHAR2(1000),
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE          DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_FLOORS PRIMARY KEY (FLOOR_ID),
    CONSTRAINT FK_FLOORS_BUILDING FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(BUILDING_ID)
);

CREATE TRIGGER TRG_FLOORS_ID
  BEFORE INSERT ON FLOORS
  FOR EACH ROW
BEGIN
  IF :NEW.FLOOR_ID IS NULL THEN
    SELECT SEQ_FLOORS.NEXTVAL INTO :NEW.FLOOR_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_FLOORS_BUILDING ON FLOORS (BUILDING_ID);

-- ============================================================
-- TABLE: CUSTOMERS
-- ============================================================
CREATE TABLE CUSTOMERS (
    CUSTOMER_ID   NUMBER        NOT NULL,
    FULL_NAME     VARCHAR2(300) NOT NULL,
    MOBILE        VARCHAR2(20)  NOT NULL,
    EMAIL         VARCHAR2(200),
    NATIONAL_ID   VARCHAR2(100),
    ADDRESS       VARCHAR2(500),
    NOTES         VARCHAR2(2000),
    CREATED_BY    VARCHAR2(100),
    CREATED_DATE  DATE          DEFAULT SYSDATE,
    UPDATED_BY    VARCHAR2(100),
    UPDATED_DATE  DATE,
    CONSTRAINT PK_CUSTOMERS PRIMARY KEY (CUSTOMER_ID)
);

CREATE TRIGGER TRG_CUSTOMERS_ID
  BEFORE INSERT ON CUSTOMERS
  FOR EACH ROW
BEGIN
  IF :NEW.CUSTOMER_ID IS NULL THEN
    SELECT SEQ_CUSTOMERS.NEXTVAL INTO :NEW.CUSTOMER_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_CUSTOMERS_MOBILE ON CUSTOMERS (MOBILE);
CREATE INDEX IDX_CUSTOMERS_NAME ON CUSTOMERS (FULL_NAME);

-- ============================================================
-- TABLE: UNITS
-- ============================================================
CREATE TABLE UNITS (
    UNIT_ID      NUMBER         NOT NULL,
    UNIT_CODE    VARCHAR2(100)  NOT NULL,
    UNIT_NAME    VARCHAR2(300)  NOT NULL,
    TYPE_ID      NUMBER         NOT NULL,
    PROJECT_ID   NUMBER         NOT NULL,
    BUILDING_ID  NUMBER         NOT NULL,
    FLOOR_ID     NUMBER         NOT NULL,
    AREA         NUMBER(10,2)   NOT NULL,
    ROOMS        NUMBER         DEFAULT 0,
    BATHROOMS    NUMBER         DEFAULT 0,
    PRICE        NUMBER(15,2)   NOT NULL,
    STATUS       VARCHAR2(20)   DEFAULT 'AVAILABLE' CHECK (STATUS IN ('AVAILABLE','SOLD','RESERVED')),
    DESCRIPTION  VARCHAR2(2000),
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE           DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_UNITS PRIMARY KEY (UNIT_ID),
    CONSTRAINT UQ_UNITS_CODE UNIQUE (UNIT_CODE),
    CONSTRAINT FK_UNITS_TYPE     FOREIGN KEY (TYPE_ID)     REFERENCES UNIT_TYPES(TYPE_ID),
    CONSTRAINT FK_UNITS_PROJECT  FOREIGN KEY (PROJECT_ID)  REFERENCES PROJECTS(PROJECT_ID),
    CONSTRAINT FK_UNITS_BUILDING FOREIGN KEY (BUILDING_ID) REFERENCES BUILDINGS(BUILDING_ID),
    CONSTRAINT FK_UNITS_FLOOR    FOREIGN KEY (FLOOR_ID)    REFERENCES FLOORS(FLOOR_ID),
    CONSTRAINT CHK_UNITS_PRICE   CHECK (PRICE > 0),
    CONSTRAINT CHK_UNITS_AREA    CHECK (AREA > 0)
);

CREATE TRIGGER TRG_UNITS_ID
  BEFORE INSERT ON UNITS
  FOR EACH ROW
BEGIN
  IF :NEW.UNIT_ID IS NULL THEN
    SELECT SEQ_UNITS.NEXTVAL INTO :NEW.UNIT_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_UNITS_STATUS   ON UNITS (STATUS);
CREATE INDEX IDX_UNITS_PROJECT  ON UNITS (PROJECT_ID);
CREATE INDEX IDX_UNITS_BUILDING ON UNITS (BUILDING_ID);
CREATE INDEX IDX_UNITS_TYPE     ON UNITS (TYPE_ID);
CREATE INDEX IDX_UNITS_CODE     ON UNITS (UNIT_CODE);

-- ============================================================
-- TABLE: SALES
-- ============================================================
CREATE TABLE SALES (
    SALE_ID      NUMBER        NOT NULL,
    UNIT_ID      NUMBER        NOT NULL,
    CUSTOMER_ID  NUMBER        NOT NULL,
    SALE_DATE    DATE          NOT NULL,
    SALE_AMOUNT  NUMBER(15,2)  NOT NULL,
    NOTES        VARCHAR2(2000),
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE          DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_SALES PRIMARY KEY (SALE_ID),
    CONSTRAINT FK_SALES_UNIT     FOREIGN KEY (UNIT_ID)     REFERENCES UNITS(UNIT_ID),
    CONSTRAINT FK_SALES_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TRIGGER TRG_SALES_ID
  BEFORE INSERT ON SALES
  FOR EACH ROW
BEGIN
  IF :NEW.SALE_ID IS NULL THEN
    SELECT SEQ_SALES.NEXTVAL INTO :NEW.SALE_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_SALES_UNIT     ON SALES (UNIT_ID);
CREATE INDEX IDX_SALES_CUSTOMER ON SALES (CUSTOMER_ID);
CREATE INDEX IDX_SALES_DATE     ON SALES (SALE_DATE);

-- ============================================================
-- TABLE: UNIT_IMAGES
-- ============================================================
CREATE TABLE UNIT_IMAGES (
    IMAGE_ID     NUMBER        NOT NULL,
    UNIT_ID      NUMBER        NOT NULL,
    FILE_NAME    VARCHAR2(500) NOT NULL,
    FILE_PATH    VARCHAR2(1000) NOT NULL,
    MIME_TYPE    VARCHAR2(100),
    FILE_SIZE    NUMBER,
    IS_PRIMARY   NUMBER(1)     DEFAULT 0,
    CREATED_BY   VARCHAR2(100),
    CREATED_DATE DATE          DEFAULT SYSDATE,
    UPDATED_BY   VARCHAR2(100),
    UPDATED_DATE DATE,
    CONSTRAINT PK_UNIT_IMAGES PRIMARY KEY (IMAGE_ID),
    CONSTRAINT FK_UNIT_IMAGES_UNIT FOREIGN KEY (UNIT_ID) REFERENCES UNITS(UNIT_ID) ON DELETE CASCADE
);

CREATE TRIGGER TRG_UNIT_IMAGES_ID
  BEFORE INSERT ON UNIT_IMAGES
  FOR EACH ROW
BEGIN
  IF :NEW.IMAGE_ID IS NULL THEN
    SELECT SEQ_UNIT_IMAGES.NEXTVAL INTO :NEW.IMAGE_ID FROM DUAL;
  END IF;
END;
/

CREATE INDEX IDX_UNIT_IMAGES_UNIT ON UNIT_IMAGES (UNIT_ID);

-- ============================================================
-- SEED DATA
-- ============================================================

-- Unit Types
INSERT INTO UNIT_TYPES (TYPE_NAME, DESCRIPTION, CREATED_BY) VALUES ('شقة', 'وحدة سكنية في مبنى متعدد الطوابق', 'SYSTEM');
INSERT INTO UNIT_TYPES (TYPE_NAME, DESCRIPTION, CREATED_BY) VALUES ('فيلا', 'منزل مستقل مع حديقة', 'SYSTEM');
INSERT INTO UNIT_TYPES (TYPE_NAME, DESCRIPTION, CREATED_BY) VALUES ('دوبلكس', 'وحدة سكنية على طابقين', 'SYSTEM');
INSERT INTO UNIT_TYPES (TYPE_NAME, DESCRIPTION, CREATED_BY) VALUES ('مكتب', 'مساحة تجارية للأعمال', 'SYSTEM');
INSERT INTO UNIT_TYPES (TYPE_NAME, DESCRIPTION, CREATED_BY) VALUES ('محل تجاري', 'محل في الطابق الأرضي', 'SYSTEM');

-- Projects
INSERT INTO PROJECTS (PROJECT_NAME, LOCATION, DESCRIPTION, START_DATE, STATUS, CREATED_BY)
  VALUES ('مشروع الأندلس', 'الرياض - حي الأندلس', 'مجمع سكني فاخر في قلب الرياض', DATE '2023-01-01', 'ACTIVE', 'SYSTEM');
INSERT INTO PROJECTS (PROJECT_NAME, LOCATION, DESCRIPTION, START_DATE, STATUS, CREATED_BY)
  VALUES ('برج النخيل', 'جدة - كورنيش', 'برج سكني تجاري على الكورنيش', DATE '2023-06-01', 'ACTIVE', 'SYSTEM');
INSERT INTO PROJECTS (PROJECT_NAME, LOCATION, DESCRIPTION, START_DATE, STATUS, CREATED_BY)
  VALUES ('مجمع الفردوس', 'الدمام - حي الفردوس', 'مجمع فلل فاخرة', DATE '2022-01-01', 'COMPLETED', 'SYSTEM');

-- Buildings
INSERT INTO BUILDINGS (PROJECT_ID, BUILDING_NAME, BUILDING_CODE, FLOORS_COUNT, CREATED_BY)
  VALUES (1, 'مبنى A', 'AND-A', 10, 'SYSTEM');
INSERT INTO BUILDINGS (PROJECT_ID, BUILDING_NAME, BUILDING_CODE, FLOORS_COUNT, CREATED_BY)
  VALUES (1, 'مبنى B', 'AND-B', 8, 'SYSTEM');
INSERT INTO BUILDINGS (PROJECT_ID, BUILDING_NAME, BUILDING_CODE, FLOORS_COUNT, CREATED_BY)
  VALUES (2, 'البرج الرئيسي', 'NAK-MAIN', 25, 'SYSTEM');
INSERT INTO BUILDINGS (PROJECT_ID, BUILDING_NAME, BUILDING_CODE, FLOORS_COUNT, CREATED_BY)
  VALUES (3, 'مبنى الفلل', 'FAR-V', 2, 'SYSTEM');

-- Floors
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (1, '1', 'الطابق الأول', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (1, '2', 'الطابق الثاني', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (1, '3', 'الطابق الثالث', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (2, '1', 'الطابق الأول', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (2, '2', 'الطابق الثاني', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (3, '1', 'الطابق الأول', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (3, '5', 'الطابق الخامس', 'SYSTEM');
INSERT INTO FLOORS (BUILDING_ID, FLOOR_NUMBER, FLOOR_NAME, CREATED_BY) VALUES (3, '10', 'الطابق العاشر', 'SYSTEM');

-- Customers
INSERT INTO CUSTOMERS (FULL_NAME, MOBILE, EMAIL, NATIONAL_ID, ADDRESS, CREATED_BY)
  VALUES ('أحمد محمد العمري', '0501234567', 'ahmed@example.com', '1234567890', 'الرياض - حي النزهة', 'SYSTEM');
INSERT INTO CUSTOMERS (FULL_NAME, MOBILE, EMAIL, NATIONAL_ID, ADDRESS, CREATED_BY)
  VALUES ('فاطمة علي الزهراني', '0551234567', 'fatima@example.com', '2234567890', 'جدة - حي الصفاء', 'SYSTEM');
INSERT INTO CUSTOMERS (FULL_NAME, MOBILE, EMAIL, NATIONAL_ID, ADDRESS, CREATED_BY)
  VALUES ('خالد عبدالله الغامدي', '0561234567', 'khalid@example.com', '3234567890', 'الدمام - حي العزيزية', 'SYSTEM');
INSERT INTO CUSTOMERS (FULL_NAME, MOBILE, EMAIL, NATIONAL_ID, ADDRESS, CREATED_BY)
  VALUES ('نورة سعد القحطاني', '0571234567', 'noura@example.com', '4234567890', 'الرياض - حي الملقا', 'SYSTEM');
INSERT INTO CUSTOMERS (FULL_NAME, MOBILE, EMAIL, NATIONAL_ID, ADDRESS, CREATED_BY)
  VALUES ('محمد إبراهيم الشهري', '0581234567', 'mohammed@example.com', '5234567890', 'جدة - حي الروضة', 'SYSTEM');

-- Units (sample - admin inserts passwords via bcrypt in app seed)
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('AND-A-101', 'شقة 101 - مبنى A', 1, 1, 1, 1, 120.5, 3, 2, 850000, 'AVAILABLE', 'شقة فاخرة بإطلالة مميزة', 'SYSTEM');
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('AND-A-201', 'شقة 201 - مبنى A', 1, 1, 1, 2, 135.0, 3, 2, 920000, 'SOLD', 'شقة بإطلالة على الحديقة', 'SYSTEM');
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('AND-A-301', 'شقة 301 - مبنى A', 2, 1, 1, 3, 250.0, 5, 4, 1850000, 'AVAILABLE', 'دوبلكس فاخر', 'SYSTEM');
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('AND-B-101', 'شقة 101 - مبنى B', 1, 1, 2, 4, 115.0, 2, 2, 780000, 'AVAILABLE', 'شقة اقتصادية', 'SYSTEM');
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('NAK-1-501', 'مكتب 501 - البرج', 4, 2, 3, 6, 200.0, 0, 2, 2500000, 'AVAILABLE', 'مكتب تجاري بإطلالة على البحر', 'SYSTEM');
INSERT INTO UNITS (UNIT_CODE, UNIT_NAME, TYPE_ID, PROJECT_ID, BUILDING_ID, FLOOR_ID, AREA, ROOMS, BATHROOMS, PRICE, STATUS, DESCRIPTION, CREATED_BY)
  VALUES ('NAK-1-101', 'محل B-01 - البرج', 5, 2, 3, 6, 85.0, 0, 1, 650000, 'SOLD', 'محل تجاري في الطابق التجاري', 'SYSTEM');

-- Sales for SOLD units
INSERT INTO SALES (UNIT_ID, CUSTOMER_ID, SALE_DATE, SALE_AMOUNT, NOTES, CREATED_BY)
  VALUES (2, 1, DATE '2024-03-15', 920000, 'بيع مباشر', 'SYSTEM');
INSERT INTO SALES (UNIT_ID, CUSTOMER_ID, SALE_DATE, SALE_AMOUNT, NOTES, CREATED_BY)
  VALUES (6, 2, DATE '2024-05-20', 650000, 'بيع نقدي', 'SYSTEM');

COMMIT;
